server:
 port: ${port:8090}
 servlet:
  contextPath: /


spring:
 thymeleaf:
  cache: false
  enabled: true


security:
 oauth2:
  client:
   clientId: 374511554907-7vf6pthvg1of08p8rsoi4o8rjno0jrak.apps.googleusercontent.com
   clientSecret: 9BcLV0fM5fw3ikCMvPYFNyGK
   accessTokenUri: https://www.googleapis.com/oauth2/v3/token
   userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
   tokenName: oauth_token
   authenticationScheme: query
   clientAuthenticationScheme: form
   scope: profile email

  resource:
   userInfoUri: https://www.googleapis.com/userinfo/v2/me
   preferTokenInfo: false 